### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by kattatzu** [cryptomkt/cryptomkt-node#3]
Hola,

cuando se logra conectarse a los libros de ordenes después de unos segundos arroja este problema al intentar sincronizar los datos con jsondiffpatch.

```js
/Users/kattatzu/projects/container/node_modules/cryptomarket/node_modules/jsondiffpatch/dist/jsondiffpatch.cjs.js:731
    child = new PatchContext(context.left[name], context.delta[name]);
                                         ^

TypeError: Cannot read property '1' of undefined
    at nestedPatchFilter (/Users/kattatzu/projects/container/node_modules/cryptomarket/node_modules/jsondiffpatch/dist/jsondiffpatch.cjs.js:731:42)
    at Pipe.process (/Users/kattatzu/projects/container/node_modules/cryptomarket/node_modules/jsondiffpatch/dist/jsondiffpatch.cjs.js:273:9)
    at Processor.process (/Users/kattatzu/projects/container/node_modules/cryptomarket/node_modules/jsondiffpatch/dist/jsondiffpatch.cjs.js:234:18)
    at DiffPatcher.patch (/Users/kattatzu/projects/container/node_modules/cryptomarket/node_modules/jsondiffpatch/dist/jsondiffpatch.cjs.js:1470:29)
    at Socket.<anonymous> (/Users/kattatzu/projects/container/node_modules/cryptomarket/lib/Socket.js:377:52)
    at Socket.Emitter.emit (/Users/kattatzu/projects/container/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/Users/kattatzu/projects/container/node_modules/socket.io-client/lib/socket.js:278:10)
    at Socket.onpacket (/Users/kattatzu/projects/container/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/Users/kattatzu/projects/container/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/Users/kattatzu/projects/container/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/Users/kattatzu/projects/container/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/Users/kattatzu/projects/container/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/Users/kattatzu/projects/container/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/Users/kattatzu/projects/container/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:251:12)
    at Manager.ondata (/Users/kattatzu/projects/container/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/Users/kattatzu/projects/container/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/Users/kattatzu/projects/container/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/Users/kattatzu/projects/container/node_modules/engine.io-client/lib/socket.js:461:14)
    at WS.<anonymous> (/Users/kattatzu/projects/container/node_modules/engine.io-client/lib/socket.js:278:10)
    at WS.Emitter.emit (/Users/kattatzu/projects/container/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/Users/kattatzu/projects/container/node_modules/engine.io-client/lib/transport.js:149:8)
    at WS.Transport.onData (/Users/kattatzu/projects/container/node_modules/engine.io-client/lib/transport.js:141:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! okane-container@1.0.0 serve: `node --no-deprecation src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the okane-container@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kattatzu/.npm/_logs/2020-02-24T18_37_35_450Z-debug.log
```

**Comment by ppbustamante** [comment]
Acabos de publicar la versión 1.0.2 con la corrección de este bug. Quedo atento
